### ISSUE TITLE
how to mine this coin?

### ISSUE THREAD

**Issue by Wolf727** [larry94555/spinozacoin#1]

**Comment by larry94555** [comment]
Hi @Wolf727 

Thanks for your inquiry.

For now, this is an effort to create a new blockchain with the goal of exploring making the implementation as simple and straightforward as possible in Python 3.

I am new to Python 3 so the code will in the beginning be in need of refactoring.  If you are an experienced Python 3 developer and see any opportunities for improving the code, let me know for I am glad for the feedback or the code improvement.

It is early days for this project.   For now, I am primarily testing out ideas I have for implementing common features of bitcoin and ethereum.  :-)  If all goes well, I will write a high-level explanation of these ideas which I will host here. 

For Phase 1 (the current phase), I am working the implementation of a peer-to-peer network whose main feature is reliable  broadcast to nodes that may not be trustworthy (these "untrustworthy nodes" are not guaranteed to broadcast the received message and may alter the message received).  The goal in this phases is to have the network self-regulate.  A node that does not respond will be flagged as "down" and a node that does not echo exactly as received will be marked as "untrusted".

For Phase 2:  I will be completing the design of the blockchain which will involve support for a wallet application as well as a Turing-complete smart-contract mechanism that will be free in phase 2.  This system will server as the test network.

For Phase 3:   I will add support for spinoza coin.  I don't believe that this system will run on proof of work so there may not be a bitcoin-like mining.  It will either be a proof of stake or it will be something else.  I have some ideas which I will be testing out.  If those don't work, I will be implementing a proof-by-stake (pos) approach to validation.
